<Invader>:
    size: 40, 40
    Image:
        source: root.source
        pos: root.pos
        size: root.size
<Projectile>:
    size: 5, 25
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
<SpaceInvadersGame>:
    canvas:
        Color:
            rgba: 0, 0, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size
